<a href="https://colab.research.google.com/github/Nishanta04/Mathematics-for-AI/blob/main/Linear_Algebra_MAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Question 1: Vector Operations


In [ ]:
import numpy as np

In [ ]:
# Define the vectors
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])

print(f"Vector a: {a}")
print(f"Vector b: {b}")

Vector a: [2 4 6 8]
Vector b: [1 3 5 7]


### Vector Addition

In [ ]:
# Vector addition
vector_sum = a + b
print(f"Vector addition (a + b): {vector_sum}")

Vector addition (a + b): [ 3  7 11 15]


### Vector Subtraction

In [ ]:
# Vector subtraction
vector_difference = a - b
print(f"Vector subtraction (a - b): {vector_difference}")

Vector subtraction (a - b): [1 1 1 1]


### Dot Product

In [ ]:
# Dot product
dot_product = np.dot(a, b)
print(f"Dot product of a and b: {dot_product}")

Dot product of a and b: 100


### Euclidean Norm

In [ ]:
# Euclidean norm of each vector
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)
print(f"Euclidean norm of a: {norm_a:.4f}")
print(f"Euclidean norm of b: {norm_b:.4f}")

Euclidean norm of a: 10.9545
Euclidean norm of b: 9.1652


### Cosine Similarity

In [ ]:
# Cosine similarity
cosine_similarity = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
print(f"Cosine similarity between a and b: {cosine_similarity:.4f}")

Cosine similarity between a and b: 0.9960


## Question 2: Matrix Operations

In [ ]:
# Define the matrices
A = np.array([[2, 1, 3], [4, 5, 2], [1, 2, 4]])
B = np.array([[1, 2, 1], [3, 1, 2], [2, 4, 3]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

Matrix A:
 [[2 1 3]
 [4 5 2]
 [1 2 4]]

Matrix B:
 [[1 2 1]
 [3 1 2]
 [2 4 3]]


### Matrix Addition (A + B)

In [ ]:
# Calculate A + B
matrix_sum = A + B
print("A + B:\n", matrix_sum)

A + B:
 [[3 3 4]
 [7 6 4]
 [3 6 7]]


### Matrix Subtraction (A - B)

In [ ]:
# Calculate A - B
matrix_difference = A - B
print("A - B:\n", matrix_difference)

A - B:
 [[ 1 -1  2]
 [ 1  4  0]
 [-1 -2  1]]


### Matrix Product (AB)

In [ ]:
# Calculate the matrix product AB
matrix_product = np.dot(A, B)
print("Matrix Product (AB):\n", matrix_product)

Matrix Product (AB):
 [[11 17 13]
 [23 21 20]
 [15 20 17]]


### Element-wise Product of A and B

In [ ]:
# Calculate the element-wise product of A and B
element_wise_product = A * B
print("Element-wise Product of A and B:\n", element_wise_product)

Element-wise Product of A and B:
 [[ 2  2  3]
 [12  5  4]
 [ 2  8 12]]


### Transpose of A

In [ ]:
# Calculate the transpose of A
transpose_A = A.T
print("Transpose of A:\n", transpose_A)

Transpose of A:
 [[2 4 1]
 [1 5 2]
 [3 2 4]]


### Trace of A

In [ ]:
# Calculate the trace of A
trace_A = np.trace(A)
print("Trace of A:", trace_A)

Trace of A: 11


## Question 3: Determinant and Inverse

In [ ]:
# Define the matrix A for Question 3
A_q3 = np.array([[4, 2, 1], [2, 5, 3], [1, 3, 6]])
print("Matrix A for Question 3:\n", A_q3)

Matrix A for Question 3:
 [[4 2 1]
 [2 5 3]
 [1 3 6]]


### Determinant of A

In [ ]:
# Calculate the determinant of A
determinant_A = np.linalg.det(A_q3)
print(f"Determinant of A: {determinant_A:.4f}")

Determinant of A: 67.0000


### Singular or Non-singular

In [ ]:
# Determine whether the matrix is singular or non-singular
# A matrix is singular if its determinant is zero.
if np.isclose(determinant_A, 0):
    print("The matrix A is singular.")
else:
    print("The matrix A is non-singular.")

The matrix A is non-singular.


### Inverse of A

In [ ]:
# Calculate the inverse of A
inverse_A = np.linalg.inv(A_q3)
print("Inverse of A:\n", inverse_A)

Inverse of A:
 [[ 0.31343284 -0.13432836  0.01492537]
 [-0.13432836  0.34328358 -0.14925373]
 [ 0.01492537 -0.14925373  0.23880597]]


### Verify the Inverse (AA⁻¹)

In [ ]:
# Verify the inverse by calculating AA⁻¹
verification = np.dot(A_q3, inverse_A)
print("A * A⁻¹:\n", verification)
# Ideally, this should be close to the identity matrix.

A * A⁻¹:
 [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.64291930e-17 1.00000000e+00 2.77555756e-17]
 [1.73472348e-17 0.00000000e+00 1.00000000e+00]]


## Question 4: Solving a System of Linear Equations

### Representing the System in AX = b

In [ ]:
# Represent the system of linear equations in the form AX = b
# A is the coefficient matrix
A_system = np.array([[2, 1, 1], [1, 3, 2], [1, 2, 4]])

# b is the constants vector
b_system = np.array([10, 13, 18])

print("Coefficient Matrix A:\n", A_system)
print("\nConstants Vector b:\n", b_system)

Coefficient Matrix A:
 [[2 1 1]
 [1 3 2]
 [1 2 4]]

Constants Vector b:
 [10 13 18]


### Solve the System using `numpy.linalg.solve()`

In [ ]:
# Solve the system for X (x, y, z)
solution_X = np.linalg.solve(A_system, b_system)

print(f"Solution (x, y, z): {solution_X}")
print(f"x = {solution_X[0]:.4f}")
print(f"y = {solution_X[1]:.4f}")
print(f"z = {solution_X[2]:.4f}")

Solution (x, y, z): [2.76923077 1.30769231 3.15384615]
x = 2.7692
y = 1.3077
z = 3.1538


### Verify the Solution

In [ ]:
# Verify the solution by substituting the obtained values back into the original equations
x, y, z = solution_X

eq1_check = 2*x + y + z
eq2_check = x + 3*y + 2*z
eq3_check = x + 2*y + 4*z

print(f"Equation 1 check (2x + y + z): {eq1_check:.4f} (Expected: 10)")
print(f"Equation 2 check (x + 3y + 2z): {eq2_check:.4f} (Expected: 13)")
print(f"Equation 3 check (x + 2y + 4z): {eq3_check:.4f} (Expected: 18)")

# Using np.allclose for more robust floating point comparison
print(f"All equations satisfied: {np.allclose([eq1_check, eq2_check, eq3_check], [10, 13, 18])}")

Equation 1 check (2x + y + z): 10.0000 (Expected: 10)
Equation 2 check (x + 3y + 2z): 13.0000 (Expected: 13)
Equation 3 check (x + 2y + 4z): 18.0000 (Expected: 18)
All equations satisfied: True


### Determinant of A and its Relationship to Unique Solution

In [ ]:
# Calculate the determinant of A_system
determinant_A_system = np.linalg.det(A_system)
print(f"Determinant of A_system: {determinant_A_system:.4f}")

# Explain the relationship
if np.isclose(determinant_A_system, 0):
    print("\nSince the determinant is approximately zero, the matrix A is singular. This means the system of equations either has no solution or infinitely many solutions. It does not have a unique solution.")
else:
    print("\nSince the determinant is non-zero, the matrix A is non-singular (invertible). This guarantees that the system of linear equations has a unique solution.")

Determinant of A_system: 13.0000

Since the determinant is non-zero, the matrix A is non-singular (invertible). This guarantees that the system of linear equations has a unique solution.


## Question 5: Linear Algebra in a Simple AI Model

In [ ]:
# Define the feature matrix X, weight vector w, and bias b
X = np.array([[2, 3], [4, 5], [6, 7], [8, 9]])
w = np.array([0.5, 1.2])
b = 2

print("Feature Matrix X:\n", X)
print("\nWeight Vector w:", w)
print("Bias b:", b)

Feature Matrix X:
 [[2 3]
 [4 5]
 [6 7]
 [8 9]]

Weight Vector w: [0.5 1.2]
Bias b: 2


### Calculate Model Output (y = Xw + b)

In [ ]:
# Calculate the model output using y = Xw + b
model_output = np.dot(X, w) + b

print("Model Output (predicted values y):\n", model_output)

Model Output (predicted values y):
 [ 6.6 10.  13.4 16.8]


### Display Predicted Values

In [ ]:
# Display the predicted value for each sample
for i, prediction in enumerate(model_output):
    print(f"Sample {i+1} Predicted Value: {prediction:.4f}")

Sample 1 Predicted Value: 6.6000
Sample 2 Predicted Value: 10.0000
Sample 3 Predicted Value: 13.4000
Sample 4 Predicted Value: 16.8000


### Change Weight Values and Observe Prediction Changes

In [ ]:
# Change the weight values
new_w = np.array([1.0, 0.8])
new_b = 0.5 # Also change bias for more noticeable change

print("\nNew Weight Vector w:", new_w)
print("New Bias b:", new_b)

# Recalculate model output with new weights and bias
new_model_output = np.dot(X, new_w) + new_b

print("\nNew Model Output (predicted values y):\n", new_model_output)

# Display new predicted values
for i, prediction in enumerate(new_model_output):
    print(f"Sample {i+1} New Predicted Value: {prediction:.4f}")

print("\nAs you can see, changing the weights and bias significantly alters the predicted values.")


New Weight Vector w: [1.  0.8]
New Bias b: 0.5

New Model Output (predicted values y):
 [ 4.9  8.5 12.1 15.7]
Sample 1 New Predicted Value: 4.9000
Sample 2 New Predicted Value: 8.5000
Sample 3 New Predicted Value: 12.1000
Sample 4 New Predicted Value: 15.7000

As you can see, changing the weights and bias significantly alters the predicted values.


## Question 6: Application Problem — Solving Multiple Systems

In [ ]:
# Define the matrix A and vectors b1 and b2
A_app = np.array([[3, 1], [2, 4]])
b1_app = np.array([10, 12])
b2_app = np.array([7, 14])

print("Matrix A:\n", A_app)
print("\nVector b₁:", b1_app)
print("Vector b₂:", b2_app)

Matrix A:
 [[3 1]
 [2 4]]

Vector b₁: [10 12]
Vector b₂: [ 7 14]


### Solve AX = b₁

In [ ]:
# Solve AX = b₁
sol_b1 = np.linalg.solve(A_app, b1_app)
print(f"Solution for AX = b₁: {sol_b1}")

Solution for AX = b₁: [2.8 1.6]


### Solve AX = b₂

In [ ]:
# Solve AX = b₂
sol_b2 = np.linalg.solve(A_app, b2_app)
print(f"Solution for AX = b₂: {sol_b2}")

Solution for AX = b₂: [1.4 2.8]
